[package]
name = "sap"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
cpython = "0.7"
pyo3 = "0.18.1"

[lib]
name = "sap"
crate-type = ["rlib", "dylib"]